maintitle: Resources Documentation
title: Intuitive Systems Resources Documentation
email: support@intuitivesystems.co.uk
description: 
baseurl: "/Resources"
url: "http://intuitivedocs.github.io/Resources/"
fixedNav: 'false'
theme: grey
styleurl: "/DocumentationSiteThemes"
fullstyleurl: "http://intuitivedocs.github.io/DocumentationSiteThemes"
contentsref: "/Resources/content/" 

# collections
collections:
     content:
        output: true

defaults:
-
  scope:
    path: ""
    type: "content"
  values:
    layout: "post"


layouts_dir: ./Jekyll/_layouts
includes_dir: ./Jekyll/_includes
pages_dir: .Jekyll/_pages


# Build settings
permalink: :title.html
markdown: kramdown
include: [_pages,categories]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

